[package]
name = "stitching_server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.7.7", default-features = false, features = [
    "http1",
    "matched-path",
    "tokio",
    "tracing",
    "ws",
] }
clap = { version = "4.5.20", default-features = false, features = [
    "derive",
    "std",
] }
futures.workspace = true
futures-util = "0.3.31"
kanal.workspace = true
nokhwa.workspace = true
tokio = { workspace = true }
tower-http = { version = "0.6.1", features = ["fs", "trace"] }
tracing.workspace = true
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
zerocopy = { version = "0.8.9", features = ["alloc"] }

[dependencies.stitch]
path = "../stitch"
default-features = false
features = ["toml-cfg", "live", "gpu"]
