[package]
name = "stitch"
version = "0.1.0"
edition = "2021"

[features]
default = ["toml-cfg", "watch", "tokio", "live", "gpu"]
toml-cfg = ["dep:toml"]
watch = ["dep:notify"]
tokio = ["dep:tokio"]
live = ["dep:nokhwa", "dep:zerocopy", "tokio", "tokio/rt"]
gpu = ["dep:smpgpu", "dep:glam"]

[dependencies]
encase = { version = "0.10.0", features = ["glam"] }
futures.workspace = true
glam = { version = "0.29.2", optional = true }
image.workspace = true
kanal.workspace = true
nokhwa = { workspace = true, optional = true }
notify = { version = "7.0.0", optional = true }
rayon = "1.10.0"
serde = { version = "1.0.214", features = ["derive"] }
smpgpu = { path = "../smpgpu", optional = true }
thiserror = "1.0.67"
tokio = { workspace = true, optional = true, features = ["sync"] }
toml = { version = "0.8.19", optional = true }
tracing.workspace = true

zerocopy = { version = "0.8.9", optional = true, features = [
    "alloc",
    "derive",
] }
