[proj]
pos = [0, 0, 4]
pitch = 0
azimuth = 0
fov = { H = 80 }
avg_colors = false
style.hemisphere = { radius = 70 }

[[cameras]]
pos = [0, -16.17, 16.6]
pitch = 0.13
azimuth = 0
roll = 0
img_off = [15, 66]
fov = { W = 148 }
lens = "equidistant"
live_index = 8
mask_path = "assets/tail-mask.png"

[[cameras]]
pos = [-4.14, -1.93, 6.68]
pitch = 0
azimuth = -115
roll = 0
img_off = [15, 66]
fov = { W = 148 }
lens = "equidistant"
live_index = 0
mask_path = "assets/left-mask.png"

[[cameras]]
pos = [4.14, -1.93, 6.68]
pitch = 0
azimuth = 115
roll = 0
img_off = [15, 66]
fov = { W = 148 }
lens = "equidistant"
live_index = 4
mask_path = "assets/right-mask.png"
