[proj]
x = 0
y = 0
z = 4
pitch = 0
azimuth = 0
fov = { H = 80 }
avg_colors = false
style = { Hemisphere = { radius = 100 } }

[[cameras]]
x = 4.14
y = -1.93
z = 6.8
pitch = 0
azimuth = 115
roll = 0
fov = { W = 150 }
lens = "equidistant"
live_index = 0

[[cameras]]
x = -4.14
y = -1.93
z = 6.8
pitch = 0
azimuth = -115
roll = 0
fov = { W = 150 }
lens = "equidistant"
live_index = 8

[[cameras]]
x = 0
y = -16.8
z = 16.76
pitch = -0.13
azimuth = 0
roll = 0
fov = { W = 150 }
lens = "equidistant"
live_index = 4
