[package]
name = "tensorrt-sys"
version = "0.1.0"
edition = "2021"

[features]
default = []
build = []

[dependencies]
cpp-interop = { version = "0.1.0", path = "../cpp-interop" }

[build-dependencies]
bindgen.workspace = true
