[package]
name = "tensorrt"
version = "0.1.0"
edition = "2021"

[features]
tracing = ["dep:tracing"]

[dependencies]
tensorrt-sys = { path = "../tensorrt-sys" }
tracing = { workspace = true, optional = true }
